spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5438/company
    username: ${POSTGRES_USER_FILE:user}
    password: ${POSTGRES_PASSWORD_FILE:pass}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: COMPANY-SERVICE

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
